# Generated by Django 4.0.1 on 2023-06-07 21:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=400)),
                ('phase_description', models.TextField()),
                ('phase_reward', models.ImageField(upload_to='')),
                ('phase_further_reading', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=400)),
                ('project_description', models.TextField()),
                ('project_deadline', models.DateField()),
                ('project_startdate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='To_Do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do_name', models.CharField(max_length=400)),
                ('to_do_description', models.TextField()),
                ('to_do_is_done', models.BooleanField(default=False)),
                ('to_do_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_Dos', to='phase_planner.phase')),
                ('to_do_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_Dos', to='phase_planner.project')),
            ],
        ),
    ]
