# Generated by Django 4.0.1 on 2023-06-07 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phase_planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='phase_reward',
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase_further_reading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=300)),
                ('reward_description', models.TextField()),
                ('reward_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('reward_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='phase_planner.phase')),
            ],
        ),
    ]
