# Generated by Django 4.0.1 on 2023-08-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase_planner', '0002_remove_phase_phase_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
