# Generated by Django 4.0.1 on 2023-06-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
